//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a Tigersong Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Haibin Jiang
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using System.Runtime.CompilerServices;

namespace Tigersong.Model
{
	/// <summary>
	/// 
	/// </summary>
	public abstract class BaseModel
	{
		/// <summary>
		/// 
		/// </summary>
		public object Id
		{
			get;
			set;
		}

		/// <summary>
		/// 
		/// </summary>
		protected BaseModel()
		{
		}
	}
}