//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a Tigersong Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Haibin Jiang
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Tigersong.Common
{
    /// <summary>
    /// 捕获异常信息记录到日志
    /// </summary>
	public class TsException : ApplicationException
    {
        public TsException()
        {
            Log.Error(Message, this);
        }

        public TsException(string message) : base(message)
        {
            Log.Error(message, this);
        }

        public TsException(string message, Exception inner) : base(message, inner)
        {
            Log.Error(message, inner);
        }
    }
}