//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a Tigersong Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Haibin Jiang
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Tigersong.ServiceProvider
{
	/// <summary>
	/// 服务提供者程序集
	/// </summary>
	public class Item
	{
		/// <summary>
		/// 程序集名
		/// </summary>
		public string Assembly
		{
			get;
			set;
		}
		/// <summary>
		/// 接口名
		/// </summary>
		public string Interface
		{
			get;
			set;
		}
		/// <summary>
		/// 命名空间
		/// </summary>
		public string NameSpace
		{
			get;
			set;
		}

		public Item()
		{
		}
	}
}
