//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a Tigersong Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Haibin Jiang
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Tigersong.AOPProxy
{
    /// <summary>
    /// 执行流程行为
    /// </summary>
    public enum FlowBehavior
    {
        /// <summary>
        /// 继续
        /// </summary>
		Continue,
        /// <summary>
        /// 抛异常
        /// </summary>
		ThrowException,
        /// <summary>
        /// 返回
        /// </summary>
		Return
    }
}
