//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a Tigersong Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Haibin Jiang
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Tigersong.AOPProxy
{
    /// <summary>
    /// 表示该方法为注入方法
    /// </summary>
	[AttributeUsage(AttributeTargets.Method)]
    public class Interception : Attribute
    {
        /// <summary>
        /// 待注入的目标方法名称
        /// </summary>
		public string TargetMethodName
        {
            get;
            set;
        }

        /// <summary>
        /// 注入目标方法的类
        /// </summary>
		public Type TargetType
        {
            get;
            set;
        }

        /// <summary>
        /// 注入目标方法的类
        /// </summary>
		public InterceptionType Type
        {
            get;
            set;
        }

        /// <summary>
        /// 注入方法
        /// </summary>
        /// <param name="targetType">注入目标方法的类</param>
        /// <param name="targetMethodName">待注入的目标方法名称</param>
        /// <param name="type">注入的类型</param>
        public Interception(Type targetType, string targetMethodName, InterceptionType type)
        {
            TargetType = targetType;
            TargetMethodName = targetMethodName;
            Type = type;
        }
    }
}
