//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a Tigersong Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Haibin Jiang
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Newtonsoft.Json;
using Tigersong.Common;

namespace Tigersong.AOPProxy
{
	/// <summary>
	/// 方法的参数
	/// </summary>
	public class MethodParameters
	{
		/// <summary>
		/// 参数
		/// </summary>
		internal object[] Argugemts
		{
			get;
			set;
		}

		/// <summary>
		/// 异常
		/// </summary>
		public Exception Exception
		{
			get;
			set;
		}

		/// <summary>
		/// 方法执行流程控制
		/// </summary>
		public FlowBehavior MethodFlow
		{
			get;
			set;
		}

		/// <summary>
		/// 返回值
		/// </summary>
		public object ReturnValue
		{
			get;
			set;
		}


		public MethodParameters(object[] agugemts)
		{
			MethodFlow = FlowBehavior.Continue;
			Argugemts = agugemts;
		}

		/// <summary>
		/// 深复制
		/// </summary>
		/// <param name="obj">待复制的对象</param>
		/// <returns></returns>
		private object DeepColne(object obj)
		{
			return JsonConvert.DeserializeObject(JsonConvert.SerializeObject(obj));
		}

		/// <summary>
		/// 获取参数
		/// </summary>
		/// <param name="index">参数序号</param>
		/// <returns></returns>
		public object GetParameter(int index)
		{
			if (index < 0)
			{
				throw new TsException("获取参数时，参数序号必须大于或等于0");
			}
			if (index >= Argugemts.Length)
			{
				throw new TsException("获取参数时，参数序号超出参数列表参数个数");
			}
			return Argugemts[index];
		}

		/// <summary>
		/// 设置参数
		/// </summary>
		/// <param name="index"></param>
		/// <param name="value"></param>
		public void SetParameter(int index, object value)
		{
			if (index < 0)
			{
				throw new TsException("设置参数时，参数序号必须大于或等于0");
			}
			if (index >= Argugemts.Length)
			{
				throw new TsException("设置参数时，参数序号超出参数列表参数个数");
			}
			Argugemts[index] = value;
		}
	}
}
