//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a Tigersong Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Haibin Jiang
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Tigersong.IServices;
using Tigersong.ServiceProvider;

namespace Tigersong.Web.Framework
{
	/// <summary>
	/// 服务类
	/// </summary>
	public static class ServiceHelper
	{
		public static T Create<T>()
		where T : IService
		{
			T create = Instance<T>.Create;
			return create;
		}
	}
}
