//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a Tigersong Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Haibin Jiang
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Tigersong.Entity;

namespace Tigersong.Service
{
	/// <summary>
	/// 
	/// </summary>
	public class ServiceBase
    {
		/// <summary>
		/// 
		/// </summary>
        protected TsDBEntity context;
         
		/// <summary>
		/// 
		/// </summary>
		public ServiceBase()
		{
            context = new TsDBEntity();
		}

		/// <summary>
		/// 
		/// </summary>
		public void Dispose()
		{
			if (context != null)
			{
                context.Dispose();
			}
		}
	}
}