//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a Tigersong Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Haibin Jiang
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Tigersong.IServices;
using Tigersong.Model;

namespace Tigersong.Service
{
    /// <summary>
    /// 
    /// </summary>
    public class UserService : ServiceBase, IUserService
    {
        /// <summary>
        /// 
        /// </summary>
        /// <param name="username"></param>
        /// <returns></returns>
        public User GetUserInfo(string username)
        {
            var model = context.Users.FirstOrDefault(a => a.UserName == username);
            return model;
        }
    }
}
